[build]
  base = "client"
  command = "npm run build"

[build.environment]
  SECRETS_SCAN_ENABLED = "false"
  CI = "false"
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  NEXT_PUBLIC_SUPABASE_URL = "https://ghkviwcymbldnitaqbav.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "sb_publishable_DDxTjVbPWBlxPnHuHsnpJQ_5kQRe3vV"

[[plugins]]
  package = "@netlify/plugin-nextjs"
